# Generated by Django 2.2.1 on 2021-02-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_liked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
