# Generated by Django 2.2.1 on 2021-02-07 11:44

import blog.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('avatar', models.ImageField(upload_to=blog.helper.PathAndRename('avatars/'), verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Администрация',
                'verbose_name_plural': 'Администрация',
            },
        ),
        migrations.CreateModel(
            name='Honours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('avatar', models.ImageField(upload_to=blog.helper.PathAndRename('avatars/'), verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Отличники образования',
                'verbose_name_plural': 'Отличники образования',
            },
        ),
        migrations.CreateModel(
            name='OurPrides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('avatar', models.ImageField(upload_to=blog.helper.PathAndRename('avatars/'), verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Ими гордится школа',
                'verbose_name_plural': 'Ими гордится школа',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('avatar', models.ImageField(upload_to=blog.helper.PathAndRename('avatars/'), verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Педагогический состав',
                'verbose_name_plural': 'Педагогический состав',
            },
        ),
    ]
