# Generated by Django 2.2.1 on 2021-02-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_administration_honours_ourprides_teachers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_posted',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
