# Generated by Django 2.2.1 on 2021-02-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210207_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Honours',
            new_name='Honour',
        ),
        migrations.RenameModel(
            old_name='OurPrides',
            new_name='OurPride',
        ),
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
