# Generated by Django 2.2.1 on 2021-02-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210207_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administration',
            old_name='avatar',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='honour',
            old_name='avatar',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='ourpride',
            old_name='avatar',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='avatar',
            new_name='image',
        ),
    ]
